worker_processes auto;

events {
    worker_connections 1024;
}

http {
    lua_package_path "/usr/local/openresty/lualib/?.lua;;";
    lua_package_cpath "./?.so;;";

    include /usr/local/openresty/nginx/conf/mime.types;
    default_type application/octet-stream;

    log_format main escape=none '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"'
                    'Request Body: $request_body';

    access_log /usr/local/openresty/nginx/logs/access.log main;
    error_log /usr/local/openresty/nginx/logs/error.log warn;

    # Trust HAProxy forwarded IPs
    set_real_ip_from 172.30.0.0/24;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    upstream haproxy_backend {
        server haproxy:80;  # HAProxy container
    }

    server {
        listen 80;
        server_name _;

        # Modify body for POST requests
        rewrite_by_lua_block {
            local cjson = require("cjson")
            ngx.req.read_body()
            local data = ngx.req.get_body_data()
            
            if data then
                local success, body = pcall(cjson.decode, data)
                if success and type(body) == "table" then
                    body["source_ip"] = ngx.var.remote_addr
                    ngx.req.set_body_data(cjson.encode(body))
                end
            end
        }

        location / {
            proxy_pass http://haproxy_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket Support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}